services:
  nginx:
    image: nginx:1.31.5-alpine
    restart: unless-stopped
    ports:
      - $LISTEN_IP:$LISTEN_PORT:80
    environment:
      - UPSTREAM_ENDPOINT=$UPSTREAM_ENDPOINT
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
