services:
  nginx:
    image: nginx:1.31.5-alpine
    restart: unless-stopped
    ports:
      - $LISTEN_IP:$LISTEN_PORT:80
    environment:
      - TARGET_HOSTNAME=$TARGET_HOSTNAME
      - TARGET_PATH=$TARGET_PATH
      - DNS_RESOLVER=$DNS_RESOLVER
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
